// Hồ sơ nhập môn: một số hoạt động/nguyên liệu/điểm đến tiêu biểu, không phải danh mục đầy đủ.
// Diện tích của địa phương hợp nhất: Nghị quyết 202/2025/QH15; Quảng Ninh: NQ 36/2026/QH16.
// Diện tích của địa phương không hợp nhất: cổng thông tin địa phương, xem areaSource.
const mergerSource='https://xaydungchinhsach.chinhphu.vn/chi-tiet-34-don-vi-hanh-chinh-cap-tinh-tu-12-6-2025-119250612141845533.htm';
const sources={
  'Hà Nội':'https://hanoi.gov.vn/tin-tuc-su-kien-noi-bat/quy-hoach-thu-do-tam-nhin-100-nam-chuyen-tu-tu-duy-quy-hoach-han-lam-sang-quy-hoach-hanh-dong-4260327154939862.htm',
  'Cao Bằng':'https://vov.gov.vn/ten-goi-56-phuong-xa-moi-cua-cao-bang-dtnew-1079197?keyDevice=true',
  'Tuyên Quang':'https://www.tuyenquang.gov.vn/vi/post/quoc-hoi-chinh-thuc-thong-qua-nghi-quyet-ca-nuoc-co-34-tinh-thanh-pho?id=148926&type=NEWS',
  'Điện Biên':'https://dienbien.gov.vn/',
  'Lai Châu':'https://xaydungchinhsach.chinhphu.vn/tham-dinh-de-an-sap-xep-don-vi-hanh-chinh-cap-xa-cua-tinh-lai-chau-119250428094632914.htm',
  'Sơn La':'https://truongchinhtri.sonla.gov.vn/index.php?act=view&id=836&module=news',
  'Lạng Sơn':'https://moha.gov.vn/tintuc/Pages/lists.aspx?ItemID=57119',
  'Quảng Ninh':'https://quangninh.gov.vn/Trang/ChiTietTinTuc.aspx?nid=168690',
  'Thanh Hóa':'https://investinthanhhoa.gov.vn/vi/',
  'Nghệ An':'https://xaydung.nghean.gov.vn/tin-hoat-dong/ban-thuong-vu-tinh-uy-ban-chap-hanh-dang-bo-tinh-thong-qua-de-an-sap-xep-to-chuc-lai-don-vi-hanh-723808',
  'Hà Tĩnh':'https://xuctiendautu.hatinh.gov.vn/vi/bai-viet/vi-tri-chien-luoc-ha-tinh',
  'Huế':'https://xaydungchinhsach.chinhphu.vn/nghi-quyet-so-175-2024-qh15-thanh-lap-thanh-pho-hue-truc-thuoc-trung-uong-119241205102339073.htm'
};

// name | area km² | terrain | climate | industry | agriculture | specialties | places | environment
const rows=`Hà Nội|3.359,84|Đồng bằng sông Hồng và đồi núi phía tây|Nhiệt đới gió mùa; mùa đông lạnh hơn mùa hè|Công nghệ, điện tử, cơ khí và chế biến thực phẩm|Rau, hoa, lúa ở các khu vực ngoại thành|Cốm làng Vòng; bánh cuốn Thanh Trì|Hồ Hoàn Kiếm; khu di tích Hoàng thành Thăng Long|Đô thị cần thích ứng ngập úng và cải thiện chất lượng không khí
Cao Bằng|6.700,39|Núi đá vôi, thung lũng và các sông suối vùng biên|Mùa đông lạnh; mùa mưa thường tập trung vào mùa hạ|Chế biến nông lâm sản và vật liệu xây dựng|Hạt dẻ, cây ăn quả ôn đới và chăn nuôi|Bánh khảo; hạt dẻ Trùng Khánh|Thác Bản Giốc; động Ngườm Ngao|Địa hình dốc đòi hỏi giữ rừng đầu nguồn và phòng sạt lở
Tuyên Quang|13.795,50|Cao nguyên đá phía bắc và vùng núi, thung lũng sông Lô|Phân hóa theo độ cao; mùa đông lạnh ở vùng núi cao|Thủy điện, chế biến gỗ và nông sản|Cam, chè và cây dược liệu|Chè Shan tuyết; cam sành Hàm Yên|Cao nguyên đá Đồng Văn; khu di tích Tân Trào|Cần giữ cảnh quan đá vôi và rừng đầu nguồn
Điện Biên|9.539,93|Lòng chảo Điện Biên và núi cao Tây Bắc|Mùa đông lạnh, mùa mưa hạ; khác biệt theo độ cao|Thủy điện và chế biến nông sản|Lúa gạo lòng chảo, cà phê và chăn nuôi|Gạo Điện Biên; thịt trâu gác bếp|Di tích Điện Biên Phủ; hồ Pá Khoang|Địa hình dốc nhạy cảm với lũ quét và sạt lở
Lai Châu|9.068,73|Dãy núi cao, thung lũng sâu và đèo Tây Bắc|Núi cao mát lạnh; mùa mưa hạ rõ rệt|Thủy điện, chế biến nông lâm sản|Chè, mắc ca và cây dược liệu|Chè Tân Uyên; lợn cắp nách|Đèo Ô Quy Hồ; động Pu Sam Cáp|Bảo vệ rừng và an toàn vùng núi dốc
Sơn La|14.109,83|Cao nguyên Mộc Châu, núi và hồ sông Đà|Phân hóa theo cao độ; cao nguyên tương đối mát|Thủy điện, chế biến sữa và nông sản|Chè, cây ăn quả, sữa và cà phê|Sữa Mộc Châu; mận hậu|Cao nguyên Mộc Châu; hồ thủy điện Sơn La|Bảo vệ lưu vực sông Đà và đất canh tác trên dốc
Lào Cai|13.256,92|Hoàng Liên Sơn, núi cao và thung lũng sông Hồng|Vùng núi cao lạnh; vùng thấp nóng hơn, mưa mùa hạ|Luyện kim, khai khoáng và chế biến nông sản|Quế, chè, cây ăn quả và ruộng bậc thang|Quế Văn Yên; thắng cố|Sa Pa; Fansipan; ruộng bậc thang Mù Cang Chải|Phát triển du lịch gắn với bảo vệ sườn núi, rừng
Thái Nguyên|8.375,21|Trung du, núi thấp và hồ Núi Cốc|Nhiệt đới gió mùa; đông mát đến lạnh|Điện tử, luyện kim và chế biến chè|Chè, cây ăn quả và chăn nuôi|Chè Tân Cương; bánh chưng Bờ Đậu|Hồ Núi Cốc; ATK Định Hóa|Giám sát môi trường công nghiệp và giữ rừng đầu nguồn
Lạng Sơn|8.310,18|Núi thấp, thung lũng và nhiều khối đá vôi|Mùa đông lạnh; có thể xuất hiện rét ở vùng cao|Chế biến nông sản, vật liệu xây dựng và dịch vụ cửa khẩu|Hồi, na và các loại rau xứ lạnh|Vịt quay Lạng Sơn; hoa hồi|Động Tam Thanh; cửa khẩu Hữu Nghị|Giữ rừng và quản lý cảnh quan hang động
Quảng Ninh|6.231,27|Núi, vịnh biển, đảo và dải biên giới Đông Bắc|Ven biển ẩm, có bão; miền núi mát hơn|Khai thác than, năng lượng, cảng biển và du lịch|Nuôi trồng thủy sản, lâm nghiệp và cây ăn quả|Chả mực Hạ Long; sá sùng|Vịnh Hạ Long; đảo Cô Tô|Bảo vệ hệ sinh thái vịnh, biển đảo và môi trường khai thác
Bắc Ninh|4.718,60|Đồng bằng và trung du chuyển tiếp|Nhiệt đới gió mùa, mùa đông lạnh|Điện tử, linh kiện và công nghiệp chế tạo|Lúa, rau và cây ăn quả ở các vùng nông thôn|Bánh phu thê; vải thiều Lục Ngạn|Làng quan họ; Tây Yên Tử|Giữ không gian làng nghề, sông và vùng sinh thái trung du
Phú Thọ|9.361,38|Trung du, vùng núi và thung lũng sông|Nhiệt đới gió mùa; miền núi cao mát hơn|Cơ khí, hóa chất, chế biến giấy và nông sản|Chè, bưởi và cây ăn quả|Bưởi Đoan Hùng; cam Cao Phong|Đền Hùng; hồ Hòa Bình|Bảo vệ lưu vực sông và đa dạng sinh học vùng núi
Hải Phòng|3.194,72|Đồng bằng cửa sông, biển đảo và vùng đất phù sa|Ven biển ẩm, có mùa đông lạnh và mưa bão|Cảng biển, logistics, đóng tàu và công nghiệp chế tạo|Lúa, rau màu, nuôi trồng thủy sản|Bánh đa cua; bánh đậu xanh Hải Dương|Quần đảo Cát Bà; Côn Sơn – Kiếp Bạc|Bảo vệ vùng cửa sông, rừng ngập mặn và biển đảo
Hưng Yên|2.514,81|Đồng bằng sông Hồng thấp và bằng phẳng|Nhiệt đới gió mùa, mùa đông lạnh|Dệt may, cơ khí và công nghiệp chế biến|Lúa, nhãn và rau màu|Nhãn lồng Hưng Yên; bánh cáy|Phố Hiến; chùa Keo|Chú ý chất lượng nước sông và bảo vệ đất nông nghiệp
Ninh Bình|3.942,62|Đồng bằng, núi đá vôi và dải ven biển|Gió mùa ẩm; mùa đông lạnh, mùa hạ mưa nhiều|Cơ khí, dệt may, chế biến và du lịch|Lúa, thủy sản ven biển và cây ăn quả|Cơm cháy Ninh Bình; phở bò Nam Định|Tràng An; Tam Cốc; nhà thờ Phát Diệm|Giữ cảnh quan di sản và đất ngập nước
Thanh Hóa|11.114,71|Từ núi phía tây qua đồng bằng đến biển|Gió mùa; chịu ảnh hưởng bão và mưa lớn ven biển|Lọc hóa dầu Nghi Sơn, xi măng và chế biến|Lúa, cây ăn quả, chăn nuôi và thủy sản|Nem chua; bánh gai Tứ Trụ|Biển Sầm Sơn; Thành Nhà Hồ|Giữ rừng thượng nguồn và phòng lũ ven sông
Nghệ An|khoảng 16.486|Núi Trường Sơn, đồng bằng sông Lam và bờ biển|Mùa hạ có gió phơn nóng khô; mùa mưa có bão|Chế biến nông lâm sản, vật liệu xây dựng và công nghiệp khu kinh tế|Lúa, cam, chè và lâm nghiệp|Cháo lươn; cam Vinh|Biển Cửa Lò; Vườn quốc gia Pù Mát|Phòng lũ, hạn và bảo vệ rừng miền tây
Hà Tĩnh|5.994,31|Núi Trường Sơn, đồng bằng hẹp và dải biển|Mùa hạ nóng; mưa lớn và bão theo mùa|Luyện thép, cảng biển và công nghiệp năng lượng|Lúa, cây ăn quả và thủy sản|Kẹo cu đơ; bưởi Phúc Trạch|Biển Thiên Cầm; Ngã ba Đồng Lộc|Ứng phó bão lũ và quản lý môi trường công nghiệp
Quảng Trị|12.700,00|Trường Sơn, núi đá vôi, đồng bằng hẹp và biển|Mùa hạ có gió phơn; mưa bão, lũ cuối năm|Năng lượng, chế biến gỗ và du lịch|Lúa, hồ tiêu và chăn nuôi|Cháo canh Quảng Bình; hồ tiêu Cùa|Phong Nha – Kẻ Bàng; địa đạo Vịnh Mốc|Bảo tồn hang động, rừng và phòng lũ
Huế|4.947,11|Núi phía tây, đồng bằng sông Hương và đầm phá|Mưa lớn tập trung vào thu đông; dễ ngập lụt|Dệt may, chế biến thực phẩm và du lịch di sản|Lúa, rau màu, thủy sản đầm phá|Bún bò Huế; mè xửng|Quần thể di tích Cố đô Huế; đầm phá Tam Giang|Bảo vệ đầm phá, di sản và thích ứng ngập lụt
Đà Nẵng|11.859,59|Trường Sơn, đồng bằng ven biển và hải đảo|Ven biển nóng ẩm; mưa bão thu đông, núi mát hơn|Công nghệ, logistics, du lịch và chế biến|Lúa, cây ăn quả, nghề cá và lâm nghiệp|Mì Quảng; bê thui Cầu Mống|Phố cổ Hội An; Bà Nà; Cù Lao Chàm|Cân bằng phát triển đô thị, du lịch và bảo tồn biển
Quảng Ngãi|14.832,55|Núi cao phía tây, đồng bằng ven biển, đảo|Khí hậu phân hóa núi – biển; mưa lớn theo mùa|Lọc hóa dầu Dung Quất, chế biến và năng lượng|Lúa, mía, sâm Ngọc Linh và nghề cá|Don; tỏi Lý Sơn|Đảo Lý Sơn; núi Ngọc Linh|Bảo vệ biển đảo và rừng đầu nguồn
Gia Lai|21.576,53|Cao nguyên bazan phía tây và duyên hải phía đông|Cao nguyên có mùa khô rõ; ven biển chịu bão|Chế biến nông sản, năng lượng tái tạo và dịch vụ cảng|Cà phê, hồ tiêu, cao su và thủy sản|Cà phê Pleiku; bánh ít lá gai|Biển Quy Nhơn; Biển Hồ Pleiku|Giữ đất bazan, rừng và sinh thái biển
Khánh Hòa|8.555,86|Núi, vùng khô ven biển và các vịnh biển|Nắng nhiều ở phía nam; mưa theo mùa, vùng núi mát|Đóng tàu, chế biến thủy sản và du lịch|Nho, tỏi, nuôi trồng và đánh bắt thủy sản|Yến sào; nho Ninh Thuận|Vịnh Nha Trang; vịnh Vĩnh Hy|Tiết kiệm nước vùng khô hạn và bảo vệ rạn san hô
Đắk Lắk|18.096,40|Cao nguyên bazan và dải duyên hải Phú Yên|Cao nguyên mưa – khô rõ; ven biển chịu bão|Chế biến cà phê, gỗ và năng lượng|Cà phê, sầu riêng, lúa và thủy sản|Cà phê Buôn Ma Thuột; cá ngừ đại dương|Hồ Lắk; Gành Đá Đĩa|Bảo vệ rừng, nguồn nước và bờ biển
Lâm Đồng|24.233,07|Cao nguyên, núi rừng và dải biển phía đông|Cao nguyên mát; ven biển khô nóng hơn, phân hóa mạnh|Chế biến nông sản, khoáng sản và du lịch|Rau hoa, cà phê, thanh long và thủy sản|Dâu tây Đà Lạt; thanh long Bình Thuận|Đà Lạt; Mũi Né; Tà Đùng|Quản lý nước, rừng và tác động du lịch ven biển
Đồng Nai|12.737,18|Đồi thấp, lưu vực sông Đồng Nai và vùng biên|Nhiệt đới gió mùa, mùa mưa và mùa khô|Công nghiệp chế tạo, chế biến, logistics|Cao su, điều, trái cây và chăn nuôi|Bưởi Tân Triều; hạt điều Bình Phước|Vườn quốc gia Cát Tiên; hồ Trị An|Bảo vệ lưu vực sông và chất lượng không khí khu công nghiệp
Hồ Chí Minh|6.772,59|Đô thị, sông ngòi, vùng cửa sông và bờ biển|Nóng quanh năm, hai mùa mưa – khô|Công nghiệp chế tạo, công nghệ, cảng biển và dịch vụ|Rau, hoa, cây ăn quả, thủy sản ven biển|Cơm tấm; bánh khọt Vũng Tàu|Chợ Bến Thành; Côn Đảo; biển Vũng Tàu|Giảm ngập đô thị, ô nhiễm và xói lở bờ biển
Tây Ninh|8.536,44|Đồng bằng thấp, vùng biên và núi Bà Đen|Nóng quanh năm; mùa mưa và mùa khô rõ|Chế biến thực phẩm, dệt may và logistics cửa khẩu|Lúa, mì, mía và cây ăn quả|Bánh tráng phơi sương; muối tôm|Núi Bà Đen; hồ Dầu Tiếng|Quản lý nước hồ, đất nông nghiệp và vùng trũng
Đồng Tháp|5.938,64|Đồng bằng sông Tiền và vùng trũng Đồng Tháp Mười|Nóng quanh năm, mưa và khô phân biệt|Chế biến nông sản, thủy sản và logistics|Lúa, xoài, hoa kiểng và nuôi cá|Xoài Cao Lãnh; hủ tiếu Mỹ Tho|Làng hoa Sa Đéc; Vườn quốc gia Tràm Chim|Thích ứng lũ, hạn và xâm nhập mặn
Vĩnh Long|6.296,20|Cù lao, sông Tiền – sông Hậu và cửa biển|Nóng ẩm; mùa mưa – khô, vùng ven biển chịu mặn|Chế biến trái cây, dừa và thủy sản|Dừa, bưởi, lúa và cây ăn quả|Kẹo dừa Bến Tre; bưởi Năm Roi|Cồn Phụng; chợ nổi Trà Ôn|Giữ nguồn nước ngọt và chống sạt lở bờ sông
An Giang|9.888,91|Đồng bằng, núi Thất Sơn và biển đảo Phú Quốc|Nóng ẩm, hai mùa; ven biển chịu tác động gió mùa|Chế biến thủy sản, du lịch và kinh tế biển|Lúa, cá tra và hồ tiêu|Mắm Châu Đốc; nước mắm Phú Quốc|Núi Cấm; đảo Phú Quốc|Bảo vệ rừng đảo, nguồn nước và vùng đầu nguồn
Cần Thơ|6.360,83|Đồng bằng sông Hậu, kênh rạch và ven biển Sóc Trăng|Nóng ẩm quanh năm; mùa mưa – khô|Chế biến lương thực, thủy sản và logistics|Lúa, trái cây, nuôi trồng thủy sản|Bánh cống Sóc Trăng; bánh tét lá cẩm|Bến Ninh Kiều; chợ nổi Cái Răng|Ứng phó ngập, sạt lở bờ sông và xâm nhập mặn
Cà Mau|7.942,39|Bán đảo thấp, rừng ngập mặn và hai mặt biển|Nóng ẩm; mưa nhiều theo mùa và chịu gió biển|Chế biến thủy sản, năng lượng và kinh tế biển|Tôm, cua, lúa – tôm và lâm nghiệp ngập mặn|Cua Cà Mau; bánh tằm Ngan Dừa|Mũi Cà Mau; rừng U Minh Hạ|Giữ rừng ngập mặn và ứng phó xói lở bờ biển`;

export const provinceDetails=Object.fromEntries(rows.split('\n').map(line=>{
  const [name,area,landscape,climate,industry,agriculture,specialties,places,environment]=line.split('|');
  return [name,{area,landscape,climate,industry,agriculture,specialties,places,environment,areaSource:sources[name]||mergerSource}];
}));
